Feat/add ft-forums,BDP brands to promos and add forumpromo
Financial-Times/n-eventpromo pull request #69
Opened 2021-02-23 11:13 UTC by maxcbc

# Feat(HIVE-42): add ft-forums,BDP brands to promos and add forumpromo

## What 
- Adds a brand attribute to an eventpromo (defaults to `ft-live`, which encapsulates the existing behaviour), this allows the switching of:
    - promo background colour
    - promo brand logo
    - default promo cta text
- Adds a ctaText prop to an eventpromo, to allow the specifying of an event specific ctaText if needed.
- Adds a forumpromo component to the exports, this is a simplified version of an event promos for when we want to promote an entire ft forum (a group with an exclusive membership), rather than a specific event. This avoids having to accommodate both events and forums within the eventpromo, and allows for easier divergence if required later.
- Removes the slideshow from images in a promo if only one image is provided.

## Why
As part of the Community initiative, we want to improve discoverability of [FT Forums](https://forums.ft.com/) and the [FT Board Directors Programme](https://bdp.ft.com/) for FT.com users. There is currently little-to-no visibility of these FT products on the website currently.

## Note
The changes in this PR have been written so as to avoid changing the existing behaviour of the promo, the idea is that changes will only be seen by users when `n-magnet` and `next-magnet-api` start supporting data from these other event brands and from forums.

## Screenshots
### Eventpromo
#### FT Live Event (existing behaviour)   

<img width="776" alt="Screenshot 2021-02-23 at 10 56 04" src="https://user-images.githubusercontent.com/11778762/108835882-043dcc80-75c8-11eb-999c-03a3cae44586.png">

#### FT Forum Event

<img width="731" alt="Screenshot 2021-02-23 at 10 55 59" src="https://user-images.githubusercontent.com/11778762/108835974-2afc0300-75c8-11eb-8363-d446d815d048.png">

2021-03-18 23:02 UTC, PlamenHristov approved these changes

2021-03-19 15:26 UTC, GlynnPhillips commented on src/BrandLogo.jsx
> +    <div className={[styles['brand'], [styles['brand--ft-live']]].join(' ')}>
**Question:** What is the benefit of adding class names in this way over adding the class name as a string such as `className="brand brand--ft-live"`

2021-03-19 15:36 UTC, GlynnPhillips commented on src/BrandLogos.scss
> +		width: 100.5px;
**Question:** Whats the need for these two images to have such specific widths that they are down to half a pixel?

2021-03-19 16:29 UTC, GlynnPhillips requested changes
Mostly some stuff I would like to discuss before we move forward

2021-03-19 16:29 UTC, GlynnPhillips commented on src/BrandLogos.scss
> +		display: inarticle-block;
**Suggestion:** I think you have made a typo here?

2021-03-19 16:29 UTC, GlynnPhillips commented on src/Details.jsx
> +			<div id="details-header" hidden>
**Question:** Whats the reason for using `hidden` to remove this element?

2021-03-19 16:29 UTC, GlynnPhillips commented on src/Details.jsx
> +				<div className={styles.strapline + ' ' + styles['strapline--forum-promo']}>
Before going onto the suggestion below I still would like to understand the benefit in adding classname in this way before worrying about the consistency issues

**Suggestion:** In other files `Array.join` has been used I think we should have a consistent style

2021-03-19 16:29 UTC, GlynnPhillips commented on src/Details.jsx
> +			<div className={styles.details} style={{'background-color': props.backgroundColor}}>
**Question:** Considering the `backgroundColor` colors are all predefined is there a reason why the `style` attribute can't be replaced by a modifier class? 

Something like `details--[theme]` where [theme] is replaced with a value

2021-03-19 16:29 UTC, GlynnPhillips commented on src/Details.scss
> +	&--forum-promo {
**Suggestion (non-blocking):** This is personal opinion and maybe this project already works in this way so keeping it like this would be the right thing to do for consistency.

When using a naming convention like BEM I find that using the `&` in sass actually introduces issues rather than solving anything. For instance it's now not possible to search for this classname as a whole string and forces you to search for only portions of the class name

2021-03-19 16:29 UTC, GlynnPhillips commented on src/Details.jsx
> +			<div id="details-header" hidden>
**Suggestion:** Personal opinion but I felt its worth raising maybe as a talking point. Theres a lot of text is `div`'s throughout these files and it normally feels like we could use an element with more semantic meaning than a div.

2021-03-22 08:59 UTC, maxcbc commented on src/Details.scss
> +	&--forum-promo {
Happy to change this. I was just following the pattern used elsewhere in the repo.

2021-03-22 09:04 UTC, maxcbc commented on src/Details.jsx
> +			<div className={styles.details} style={{'background-color': props.backgroundColor}}>
My original approach was to send `brand` as a prop to each component and then do an if/else or switch statement everywhere that was brand specific in order to switch behaviour. So in this case it was 'details--${brand}' etc.

This however lead to the code being very messy, with if statements all over the place. I felt this made the code much less clear. So I switched it to being the brand preset model, where I have a group of presets at the top level which get passed down. It makes it much easier to see what is happening (IMHO).

2021-03-22 09:04 UTC, maxcbc commented on src/Details.jsx
> +				<div className={styles.strapline + ' ' + styles['strapline--forum-promo']}>
Will do

2021-03-22 09:06 UTC, maxcbc commented on src/Details.jsx
> +			<div id="details-header" hidden>
To be honest I've just copied this code like for like from the existing code and added the necessary modifications for the use case.

There are a few things in this repo I would change. Don't disagree with your substantive point. I just think it's debatable whether 'de-div-ing' is done as part of this PR or not.

2021-03-22 09:08 UTC, maxcbc commented on src/BrandLogos.scss
> +		display: inarticle-block;
Yes and no. This is copied from the existing code. https://github.com/Financial-Times/n-eventpromo/blob/master/src/Footer.scss#L63 . I'll delete it, it means nothing to me either.

2021-03-22 09:08 UTC, maxcbc commented on src/BrandLogos.scss
> +.brand--ft-bdp {
Will do.

2021-03-22 09:19 UTC, maxcbc commented on src/BrandLogos.scss
> +		width: 100.5px;
It's actually to make all the logos have the same height as the FT Live logo, which was in the designs I was given.
The FT Live Logo from origami is 300x121. In the css in this repo it is width constrained to 70px which means its height is automatically fixed to ~28.23px.

The FT BDP Logo is 300x81. So in order for to get the same ~28px height using the width constraint its width must be `70/81 * 121` px (104.57 px). I applied the same approach to the FT Forums Logo.

I could put this in as a scss calc, but I'm not sure that's any better. Is there a more elegant way of setting up this css so that the logo heights are the same?

2021-03-22 09:19 UTC, maxcbc commented on src/BrandLogo.jsx
> +    <div className={[styles['brand'], [styles['brand--ft-live']]].join(' ')}>
I think this is a refactoring error. I'll correct this.

2021-03-22 09:48 UTC, GlynnPhillips commented on src/BrandLogo.jsx
> +    <div className={[styles['brand'], [styles['brand--ft-live']]].join(' ')}>
Sorry @maxcbc I don't think I made my original question version very clear. What I am interested in is what advantages does importing the styles and then doing `className={styles['brand']}` have over just doing `className="brand"`?

2021-03-22 09:55 UTC, GlynnPhillips commented on src/BrandLogos.scss
> +.brand--ft-bdp {
Thanks 👍

2021-03-22 09:56 UTC, GlynnPhillips commented on src/Details.jsx
> +			<div id="details-header" hidden>
And do you know the reason for adding `hidden`?

2021-03-22 09:59 UTC, maxcbc commented on src/BrandLogo.jsx
> +    <div className={[styles['brand'], [styles['brand--ft-live']]].join(' ')}>
I've changed them all to template strings.

2021-03-22 10:01 UTC, GlynnPhillips commented on src/Details.jsx
> +			<div className={styles.details} style={{'background-color': props.backgroundColor}}>
When you say all over the place, how often is this happening? I can only see this 1 example.

Also would it need a if/else statement? couldn't the `brand` prop be appended to the classname, something like `className={styles.details details--${brand}}` ?

2021-03-22 10:22 UTC, maxcbc commented on src/BrandLogo.jsx
> +    <div className={[styles['brand'], [styles['brand--ft-live']]].join(' ')}>
Its because the repo has been set up to use scss in js and at publish-time this repo is transpiled. So `styles['brand']` and `.brand` are not the same, because when it gets transpiled the actual class name becomes something like `.BrandLogos_brand__1lzRM`.

If memory serves this repo was written long before pagekit and when x-dash wasn't commonplace. So there were no common patterns at that time for how we distribute jsx components. It needs a bit of work to strip all the transpilation steps out etc so it 'just works' with pagekit etc. Again another thing I want to do, but it needs to be a separate PR.

2021-03-22 10:31 UTC, GlynnPhillips commented on src/BrandLogo.jsx
> +    <div className={[styles['brand'], [styles['brand--ft-live']]].join(' ')}>
Cool, I thought that might be the case but wasn't 100% sure. Thanks

2021-03-22 10:32 UTC, maxcbc commented on src/Details.jsx
> +			<div className={styles.details} style={{'background-color': props.backgroundColor}}>
This is the only place where the style would be affected by this sort of if statement. But there are a few other things which vary with brand. So using the brand prop, we'd need an if statement in `Images.jsx` to vary the default image, an if statement in `Footer.jsx` to vary the default CTA text and BrandLogo and an if statement in `Details.jsx` to vary the classname.

But you're right in that if we were doing it'd just be a case of doing `details--${brand}`, but because of the whole css in js thing we'd probably still need an if statement to guard against the case where `styles[`details--${brand}`]` didn't exist.

2021-03-22 10:41 UTC, maxcbc commented on src/Details.jsx
> +			<div id="details-header" hidden>
replaced it with `h2.visually-hidden`.

The 'div' was there to give some context to screen readers. I'm not sure it did that. But you're right, I should be more attentive to purpose/outcomes in my copy&adapt approach. I just know I have a tendency to significantly refactor things I see as wrong which can make my PRs huge, complex and difficult to follow. Maybe I overcompensated against that.

2021-03-22 10:55 UTC, GlynnPhillips commented on src/BrandLogos.scss
> +		width: 100.5px;
Yeah that does seem a bit tricky. Question, do they have to match to that level of accuracy? They aren't seen side by side right? so would `100px` instead of `100.5px` be ok?

2021-03-22 10:59 UTC, GlynnPhillips commented on src/Details.jsx
> +			<div className={styles.details} style={{'background-color': props.backgroundColor}}>
Great that we are thinking about the bigger picture but in this case I think we can still get away with this just for the css situation. Seems nicer when using BEM to not have `style` attribute overrides. So I would still argue for doing it here and not worrying so much about the other places that are markup changes.

Regarding the safe guarding, I am not familiar with the set up here and would ask the question what happens if we don't? does it just fail to compile and therefor won't deploy? If thats the case I think it might be ok to not safeguard as you will always be aware of this when building and will need to fix it to deploy

2021-03-22 11:02 UTC, maxcbc commented on src/BrandLogos.scss
> +		width: 100.5px;
Done.

2021-03-22 11:25 UTC, maxcbc commented on src/Details.jsx
> +			<div className={styles.details} style={{'background-color': props.backgroundColor}}>
So if you do `styles[details--${brand]}` and it evaluates to 'undefined' it will add 'undefined' to the css string. Meaning if someone elsewhere somehow sets '.undefined' in the css, those styles will apply.
 
Anyway i've redone it to use a modifier class rather than a style tag. It's still passed down from the 'preset' at the top level. Tell me what you think.

2021-03-30 15:48 UTC, GlynnPhillips commented on src/Details.jsx
> +			<div className={styles.details} style={{'background-color': props.backgroundColor}}>
Yeah I think this is an improvement. Thanks

2021-03-30 15:56 UTC, GlynnPhillips requested changes
Couple of small requests but looks good other than that

2021-03-30 15:56 UTC, GlynnPhillips commented on src/BrandLogos.scss
> +	span {
**Suggestion:** I think it would be nice to give this a classname considering we are in control of that

2021-03-30 15:56 UTC, GlynnPhillips commented on src/Details.jsx
> +			<h2 id="details-header" className={commonStyles['visually-hidden']}>
**Suggestion:** As this is a component that gets used in other pages I think it would be nice to make the ID more specific so theres no chance of a clash

2021-04-01 14:40 UTC, maxcbc commented on src/BrandLogos.scss
> +	span {
Done. 🙂

2021-04-01 14:40 UTC, maxcbc commented on src/Details.jsx
> +			<h2 id="details-header" className={commonStyles['visually-hidden']}>
Have, removed the ids.

2021-04-13 09:03 UTC, GlynnPhillips approved these changes
Thanks for making the changes Max 👍

2021-04-13 09:12 UTC, maxcbc commented
Thanks for the reviews Glynn 👍  

Please can you do the merge? I don't have the perms.

2021-04-13 09:22 UTC, GlynnPhillips commented
Ohh yes I forgot you are outside of customer products now

2021-04-13 09:23 UTC, merged