[CI-1289] Toolkit migration
Financial-Times/n-eventpromo pull request #98
Opened 2022-08-12 09:14 UTC by AlbertoCuberoNavas

[https://financialtimes.atlassian.net/browse/CI-1289](https://financialtimes.atlassian.net/browse/CI-1289)

2022-08-12 11:07 UTC, juanSanchezAlcala requested changes

2022-08-12 11:07 UTC, juanSanchezAlcala commented on .toolkitrc.yml
> +hooks:
In the makefile we are doing a build with rollup , i think we have to set that here

2022-08-12 11:07 UTC, juanSanchezAlcala commented on .circleci/config.yml
> +      - tool-kit/build:
Unless we set what to do when build on .toolkitrc this wont do the rollup compilation

2022-08-16 10:38 UTC, AlbertoCuberoNavas commented on .toolkitrc.yml
> +hooks:
ok, I'll add the rollup plugin from n-exponea: [https://github.com/Financial-Times/n-exponea/blob/main/tool-kit/rollup/index.js](https://github.com/Financial-Times/n-exponea/blob/main/tool-kit/rollup/index.js )

2022-08-17 10:50 UTC, juanSanchezAlcala approved these changes

2022-08-17 10:50 UTC, merged